site_name: 'Baqend Guide'
site_url: 'https://www.baqend.com/guide'
repo_url: 'https://github.com/Baqend/guide'
pages:
    - Guide:
        - Home: 'index.md'
        - Quickstart: 'gettingstarted/index.md'
        - Roadmap: 'roadmap.md'
        - Speed Kit: 'topics/speed-kit/index.md'

        - 'Getting Started': 'topics/getting-started/index.md'
        - 'CLI': 'topics/cli/index.md'
        - 'CRUD': 'topics/crud/index.md'
        - 'Schema and Types': 'topics/schema/index.md'
        - 'Queries': 'topics/queries/index.md'
        - 'Real-Time Queries': 'topics/realtime/index.md'
        - 'User Management': 'topics/user-management/index.md'
        - 'Baqend Code': 'topics/baqend-code/index.md'
        - 'Push Notifications': 'topics/push/index.md'
        - 'Partial Updates': 'topics/partial-updates/index.md'
        - 'Deep Loading': 'topics/deep-loading/index.md'
        - 'Hosting': 'topics/hosting/index.md'
        - 'Files': 'topics/files/index.md'
        - 'Caching': 'topics/caching/index.md'
        - 'Logging': 'topics/logging/index.md'
        - 'Backups': 'topics/backups/index.md'
        #- WordPress Plugin: 'topics/wordpress/index.md'

    - Starter Kits:
        - Starter Kits Overview: 'starter-kits/index.md'
        - Angular 2 Starter Kit: 'starter-kits/angular2.md'
        - React and React Native Starter: 'starter-kits/react.md'
        - Bootstrap Starter Kit: 'starter-kits/bootstrap.md'
        - Ionic 2 Starter Kit: 'starter-kits/ionic2.md'
        - Ionic Starter Kit: 'starter-kits/ionic.md'

    - hidden:
        - 'Rest': 'rest.md'
        - 'Websockets': 'websockets.md'
docs_dir: src
site_dir: docs
theme_dir: theme
markdown_extensions: [fenced_code]
#theme: cosmo
